{
  bills {
    id
    title,
    congress,
    billType,
    billTypeLabel,
    currentChamber,
    currentStatus,
    currentStatusDate,
    currentStatusDescription,
    currentStatusLabel,
    introducedDate,
    isAlive,
    isCurrent,
    link,
    titleWithoutNumber,
    billCode
  }
}