query Bill($id: ID!) {
  bills(billId: $id) {
    id
    title
    congress
    billNumber
    introducedDate
    billType {
      display
    }
    sponsor {
      id
      roleType
      party
      state
      district
      person {
        lastname
        firstname
      }
    }
    cosponsors {
      id
      roleType
      party
      state
      district
      person {
        lastname
        firstname
      }
    }
  }
}
