query Bill($id: ID!) {
  bills(billId: $id) {
    id,
    title,
    congress,
    sponsor {
      id,
      roleType,
      party,
      state,
      district,
      person {
        lastname,
        firstname
      }
    }
  }
}