query BillsQuery($lang: String, $ids: [ID]) {
  bills(lang: $lang, ids: $ids) {
    id
    title
    congress
    billCode
    billNumber
    introducedDate
    billType {
      chamber
      code
    }
    cosponsors {
      member {
        id
      }
    }
    tags {
      tag
    }
    sponsor {
      id
      lastName
      firstName
      congressRoles {
        party
        state
        district
        title
        startDate
        endDate
      }
      profilePictures {
        tiny
      }
    }
    actions {
      datetime
      description
    }
    trackers {
      selected
      stepName
    }
  }
}
