query BillsQuery($lang: String, $ids: [ID]) {
  bills(lang: $lang, ids: $ids) {
    id
    title
    billCode
    billNumber
    congress
    introducedDate
    billType {
      id
      chamber
      code
    }
    cosponsors {
      dateCosponsored
      role {
        person {
          id
        }
      }
    }
    sponsor {
      person {
        id
      }
    }
  }
}
