query MembersQuery($lang: String, $ids: [ID]) {
  members(lang: $lang, ids: $ids) {
    id
		firstName
		lastName
		middleName
    bioGuideId
    profilePictures {
      tiny  
    }
    currentRole {
      congressNumbers
			district
	    party
      roleTypeDisplay
      senatorClass
      senatorClassDisplay
      state
      title
      titleLong
    }
    website
    billIdCosponsored
    billIdSponsored
    cosponsorProperty {
      billId
      dateCosponsored
    }
  }
}
