query ArticlesQuery($list: String, $limit: Int, $before: String) {
  articles(list: $list, limit: $limit, before: $before) {
    id
    headline
    subhead
    author
    intro
    url
    imageUrl
    date
  }
}
