query BillsQuery($lang: String, $ids: [ID]) {
  bills(lang: $lang, ids: $ids) {
    id
    title
    congress
    billCode
    billNumber
    billType {
      id
      code
    }
    actionsAll {
      datetime
      description
    }
    trackers {
      selected
      stepName
    }
  }
}
