query BillsQuery($lang: String, $ids: [ID]) {
  bills(lang: $lang, ids: $ids) {
    id
    title
    billCode
    billNumber
    congress
    introducedDate
    actions {
      datetime
      description
    }
    trackers {
      selected
      stepName
    }
    billType {
      chamber
      code
    }
    cosponsors {
      member {
        id
      }
    }
    sponsor {
      id
    }
  }
}
