query MemberQuery($lang: String, $ids: [ID]) {
  members(lang: $lang, ids: $ids) {
    id
		firstName
		lastName
		middleName
    bioGuideId
    profilePictures {
      medium
    }
    latestRole {
      congressNumbers
      district
      party
      state
      title
      titleLong
    }
    currentRole {
      title
    }
    billIdCosponsored
    billIdSponsored
    cosponsorProperty {
      billId
      dateCosponsored
    }
  }
}
