{
  bills {
    id
    title
    congress
    billCode
    categories {
      id
      name
    }
    billType {
      chamber
    }
    sponsor {
      party
      person {
        lastname
        firstname
      }
    }
  }
}
