query BillsQuery($lang: String, $ids: [ID]) {
  bills(lang: $lang, ids: $ids) {
    id
    title
    congress
    billCode
    billNumber
    introducedDate
    articles {
      id
      headline
      subhead
      author
      intro
      url
      imageUrl
      date
    }
    cosponsors {
      dateCosponsored
      member {
        id
        lastName
        firstName
        congressRoles {
          startDate
          endDate
          party
          state
          district
          title
        }
      }
    }
    billType {
      chamber
      code
    }
    sponsor {
      id
      lastName
      firstName
      profilePictures {
        tiny
      }
      congressRoles {
        startDate
        endDate
        party
        state
        district
        title
      }
    }
    versions {
      name
      date
      description
      documents {
        contentType
        s3Entity
      }
    }
    actions {
      datetime
      description
    }
    trackers {
      selected
      stepName
    }
    summary {
      title
      paragraphs
    }
  }
}
