query BillsQuery($lang: String, $ids: [ID]) {
  bills(lang: $lang, ids: $ids) {
    id
    title
    congress
    billCode
    billNumber
    introducedDate
    categories {
      id
      name
    }
    billType {
      id
      chamber
      code
    }
    sponsor {
      id
      party
      state
      district
      title
      person {
        id
        lastname
        firstname
      }
    }
    actions {
      datetime
      description
    }
    trackers {
      selected
      stepName
    }
  }
}
