query BillDetailPageQuery($lang: String, $ids: [ID]) {
  bills(lang: $lang, ids: $ids) {
    id
    title
    congress
    billCode
    billNumber
    introducedDate
    cosponsors {
      role {
        id
        party
        state
        district
        title
        person {
          id
          lastname
          firstname
        }
      }
      dateCosponsored
    }
    categories {
      id
      name
    }
    billType {
      id
      chamber
      code
    }
    sponsor {
      id
      party
      state
      district
      title
      person {
        id
        lastname
        firstname
        profilePictures {
          tiny
        }
      }
    }
    versions {
      id
      name
      date
      description
      documents {
        contentType
        s3Entity
      }
    }
    actions {
      datetime
      description
    }
    trackers {
      selected
      stepName
    }
    summary {
      title
      paragraphs
    }
  }
}
